/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedSpreadsheetRouteImport } from './routes/_authed/spreadsheet'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedCreditCardsIndexRouteImport } from './routes/_authed/credit-cards/index'
import { Route as AuthedBanksIndexRouteImport } from './routes/_authed/banks/index'
import { Route as AuthedCreditCardsCardIdRouteImport } from './routes/_authed/credit-cards/$cardId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSpreadsheetRoute = AuthedSpreadsheetRouteImport.update({
  id: '/spreadsheet',
  path: '/spreadsheet',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCreditCardsIndexRoute = AuthedCreditCardsIndexRouteImport.update({
  id: '/credit-cards/',
  path: '/credit-cards/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBanksIndexRoute = AuthedBanksIndexRouteImport.update({
  id: '/banks/',
  path: '/banks/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCreditCardsCardIdRoute = AuthedCreditCardsCardIdRouteImport.update({
  id: '/credit-cards/$cardId',
  path: '/credit-cards/$cardId',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/spreadsheet': typeof AuthedSpreadsheetRoute
  '/credit-cards/$cardId': typeof AuthedCreditCardsCardIdRoute
  '/banks/': typeof AuthedBanksIndexRoute
  '/credit-cards/': typeof AuthedCreditCardsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/spreadsheet': typeof AuthedSpreadsheetRoute
  '/credit-cards/$cardId': typeof AuthedCreditCardsCardIdRoute
  '/banks': typeof AuthedBanksIndexRoute
  '/credit-cards': typeof AuthedCreditCardsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/spreadsheet': typeof AuthedSpreadsheetRoute
  '/_authed/credit-cards/$cardId': typeof AuthedCreditCardsCardIdRoute
  '/_authed/banks/': typeof AuthedBanksIndexRoute
  '/_authed/credit-cards/': typeof AuthedCreditCardsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/spreadsheet'
    | '/credit-cards/$cardId'
    | '/banks/'
    | '/credit-cards/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/spreadsheet'
    | '/credit-cards/$cardId'
    | '/banks'
    | '/credit-cards'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/_authed/dashboard'
    | '/_authed/spreadsheet'
    | '/_authed/credit-cards/$cardId'
    | '/_authed/banks/'
    | '/_authed/credit-cards/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/spreadsheet': {
      id: '/_authed/spreadsheet'
      path: '/spreadsheet'
      fullPath: '/spreadsheet'
      preLoaderRoute: typeof AuthedSpreadsheetRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/credit-cards/': {
      id: '/_authed/credit-cards/'
      path: '/credit-cards'
      fullPath: '/credit-cards/'
      preLoaderRoute: typeof AuthedCreditCardsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/banks/': {
      id: '/_authed/banks/'
      path: '/banks'
      fullPath: '/banks/'
      preLoaderRoute: typeof AuthedBanksIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/credit-cards/$cardId': {
      id: '/_authed/credit-cards/$cardId'
      path: '/credit-cards/$cardId'
      fullPath: '/credit-cards/$cardId'
      preLoaderRoute: typeof AuthedCreditCardsCardIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedSpreadsheetRoute: typeof AuthedSpreadsheetRoute
  AuthedCreditCardsCardIdRoute: typeof AuthedCreditCardsCardIdRoute
  AuthedBanksIndexRoute: typeof AuthedBanksIndexRoute
  AuthedCreditCardsIndexRoute: typeof AuthedCreditCardsIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedSpreadsheetRoute: AuthedSpreadsheetRoute,
  AuthedCreditCardsCardIdRoute: AuthedCreditCardsCardIdRoute,
  AuthedBanksIndexRoute: AuthedBanksIndexRoute,
  AuthedCreditCardsIndexRoute: AuthedCreditCardsIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
